/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type GameResult = {
  _id: string;
  _type: "gameResult";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  gameImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  teams?: Array<{
    name?: string;
    record?: string;
    quarters?: Array<number>;
    total?: number;
    isWinner?: boolean;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Match = {
  _id: string;
  _type: "match";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  matchDay?: number;
  matchNumber?: number;
  date?: string;
  time?: string;
  location?: string;
  homeTeam?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "team";
  };
  awayTeam?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "team";
  };
  homeScore?: number;
  awayScore?: number;
  status?: "scheduled" | "completed" | "cancelled";
  competition?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "competition";
  };
};

export type Competition = {
  _id: string;
  _type: "competition";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  season?: number;
  type?: "league" | "tournament" | "preseason";
  format?: "7" | "5";
  gender?: "coed" | "men" | "women";
  startDate?: string;
  endDate?: string;
  status?: "upcoming" | "active" | "completed";
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Team = {
  _id: string;
  _type: "team";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  abbreviation?: string;
  yearFounded?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bannerImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryColor?: string;
  secondaryColor?: string;
  country?: string;
  state?: string;
  foundedYear?: number;
  headCoach?: string;
  asstHeadCoach?: string;
  players?: Array<{
    firstName?: string;
    lastName?: string;
    email?: string;
    jerseyName?: string;
    jerseyNumber?: number;
    gender?: "male" | "female" | "non-binary" | "prefer-not-to-say";
    photo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    isCaptain?: boolean;
    positions?: Array<string>;
    instagram?: string;
    _key: string;
  }>;
  socialLinks?: {
    instagram?: string;
    youtube?: string;
    tiktok?: string;
    twitter?: string;
  };
  email?: string;
  phone?: string;
  url?: string;
  isActive?: boolean;
};

export type Replay = {
  _id: string;
  _type: "replay";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  team1?: {
    name?: string;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    color?: string;
  };
  team2?: {
    name?: string;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    color?: string;
  };
};

export type Upcoming = {
  _id: string;
  _type: "upcoming";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  games?: Array<{
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    date?: string;
    week?: string;
    _key: string;
  }>;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = GameResult | SanityImageCrop | SanityImageHotspot | Match | Competition | Slug | Team | Replay | Upcoming | News | Post | BlockContent | Author | Category | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/queries/competitions/useFetchCompetitions.ts
// Variable: COMPETITIONS_QUERY
// Query: *[_type == "competition"] | order(name asc) {  _id,  name,  slug,  season,  type,  format,  gender,  startDate,  endDate,  status,  "logo": logo.asset->url,}
export type COMPETITIONS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  season: number | null;
  type: "league" | "preseason" | "tournament" | null;
  format: "5" | "7" | null;
  gender: "coed" | "men" | "women" | null;
  startDate: string | null;
  endDate: string | null;
  status: "active" | "completed" | "upcoming" | null;
  logo: string | null;
}>;

// Source: ./src/queries/competitions/useFetchSingleCompetition.ts
// Variable: COMPETITION_QUERY
// Query: *[_type == "competition" && slug.current == $slug][0] {  _id,  name,  slug,  season,  type,  format,  gender,  startDate,  endDate,  status,  "logo": logo.asset->url,}
export type COMPETITION_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  season: number | null;
  type: "league" | "preseason" | "tournament" | null;
  format: "5" | "7" | null;
  gender: "coed" | "men" | "women" | null;
  startDate: string | null;
  endDate: string | null;
  status: "active" | "completed" | "upcoming" | null;
  logo: string | null;
} | null;

// Source: ./src/queries/matches/useFetchMatches.ts
// Variable: MATCHES_QUERY
// Query: *[_type == "match"  && ($status == null || status == $status)  && ($competitionId == null || competition._ref == $competitionId)  && ($competitionSlug == null || competition->slug.current == $competitionSlug)  && ($team == null || homeTeam._ref == $team || awayTeam._ref == $team)  && ($teamSlug == null || homeTeam->slug.current == $teamSlug || awayTeam->slug.current == $teamSlug)  && ($homeTeam == null || homeTeam._ref == $homeTeam)  && ($homeTeamSlug == null || homeTeam->slug.current == $homeTeamSlug)  && ($awayTeam == null || awayTeam._ref == $awayTeam)  && ($awayTeamSlug == null || awayTeam->slug.current == $awayTeamSlug)  && ($date == null || date == $date)  && ($matchDay == null || matchDay == $matchDay)] | order(matchNumber asc) [$offset...$limit] {  _id,  matchDay,  matchNumber,  date,  time,  location,  homeScore,  awayScore,  status,  "homeTeam": homeTeam-> {    _id,    name,    "logo": logo.asset->url,  },  "awayTeam": awayTeam-> {    _id,    name,    "logo": logo.asset->url,  },  competition,}
export type MATCHES_QUERYResult = Array<{
  _id: string;
  matchDay: number | null;
  matchNumber: number | null;
  date: string | null;
  time: string | null;
  location: string | null;
  homeScore: number | null;
  awayScore: number | null;
  status: "cancelled" | "completed" | "scheduled" | null;
  homeTeam: {
    _id: string;
    name: string | null;
    logo: string | null;
  } | null;
  awayTeam: {
    _id: string;
    name: string | null;
    logo: string | null;
  } | null;
  competition: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "competition";
  } | null;
}>;
// Variable: MATCHES_COUNT_QUERY
// Query: count(*[_type == "match"  && ($status == null || status == $status)  && ($competitionId == null || competition._ref == $competitionId)  && ($competitionSlug == null || competition->slug.current == $competitionSlug)  && ($team == null || homeTeam._ref == $team || awayTeam._ref == $team)  && ($teamSlug == null || homeTeam->slug.current == $teamSlug || awayTeam->slug.current == $teamSlug)  && ($homeTeam == null || homeTeam._ref == $homeTeam)  && ($homeTeamSlug == null || homeTeam->slug.current == $homeTeamSlug)  && ($awayTeam == null || awayTeam._ref == $awayTeam)  && ($awayTeamSlug == null || awayTeam->slug.current == $awayTeamSlug)  && ($date == null || date == $date)  && ($matchDay == null || matchDay == $matchDay)])
export type MATCHES_COUNT_QUERYResult = number;

// Source: ./src/queries/matches/useFetchSingleMatch.ts
// Variable: MATCH_QUERY
// Query: *[_type == "match" && id == $id][0] {  _id,  name,  slug,  abbreviation,  yearFounded,  foundedYear,  primaryColor,  secondaryColor,  country,  state,  headCoach,  asstHeadCoach,  email,  phone,  url,  isActive,  "logo": logo.asset->url,  "bannerImage": bannerImage.asset->url,  players[] {    name,    number,    positions,    isCaptain,    "photo": photo.asset->url,  },  socialLinks {    instagram,    youtube,    tiktok,    twitter,  },}
export type MATCH_QUERYResult = {
  _id: string;
  name: null;
  slug: null;
  abbreviation: null;
  yearFounded: null;
  foundedYear: null;
  primaryColor: null;
  secondaryColor: null;
  country: null;
  state: null;
  headCoach: null;
  asstHeadCoach: null;
  email: null;
  phone: null;
  url: null;
  isActive: null;
  logo: null;
  bannerImage: null;
  players: null;
  socialLinks: null;
} | null;

// Source: ./src/queries/teams/useFetchSingleTeam.ts
// Variable: TEAM_QUERY
// Query: *[_type == "team" && isActive == true && slug.current == $slug][0] {  _id,  name,  slug,  abbreviation,  yearFounded,  foundedYear,  primaryColor,  secondaryColor,  country,  state,  headCoach,  asstHeadCoach,  email,  phone,  url,  isActive,  "logo": logo.asset->url,  "bannerImage": bannerImage.asset->url,  players[] {    name,    number,    positions,    isCaptain,    "photo": photo.asset->url,  },  socialLinks {    instagram,    youtube,    tiktok,    twitter,  },}
export type TEAM_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  abbreviation: string | null;
  yearFounded: string | null;
  foundedYear: number | null;
  primaryColor: string | null;
  secondaryColor: string | null;
  country: string | null;
  state: string | null;
  headCoach: string | null;
  asstHeadCoach: string | null;
  email: string | null;
  phone: string | null;
  url: string | null;
  isActive: boolean | null;
  logo: string | null;
  bannerImage: string | null;
  players: Array<{
    name: null;
    number: null;
    positions: Array<string> | null;
    isCaptain: boolean | null;
    photo: string | null;
  }> | null;
  socialLinks: {
    instagram: string | null;
    youtube: string | null;
    tiktok: string | null;
    twitter: string | null;
  } | null;
} | null;

// Source: ./src/queries/teams/useFetchTeams.ts
// Variable: TEAMS_QUERY
// Query: *[_type == "team" && isActive == true] | order(name asc) {  _id,  name,  slug,  abbreviation,  primaryColor,  secondaryColor,  country,  "logo": logo.asset->url,}
export type TEAMS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  abbreviation: string | null;
  primaryColor: string | null;
  secondaryColor: string | null;
  country: string | null;
  logo: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"competition\"] | order(name asc) {\n  _id,\n  name,\n  slug,\n  season,\n  type,\n  format,\n  gender,\n  startDate,\n  endDate,\n  status,\n  \"logo\": logo.asset->url,\n}": COMPETITIONS_QUERYResult;
    "*[_type == \"competition\" && slug.current == $slug][0] {\n  _id,\n  name,\n  slug,\n  season,\n  type,\n  format,\n  gender,\n  startDate,\n  endDate,\n  status,\n  \"logo\": logo.asset->url,\n}": COMPETITION_QUERYResult;
    "*[_type == \"match\"\n  && ($status == null || status == $status)\n  && ($competitionId == null || competition._ref == $competitionId)\n  && ($competitionSlug == null || competition->slug.current == $competitionSlug)\n  && ($team == null || homeTeam._ref == $team || awayTeam._ref == $team)\n  && ($teamSlug == null || homeTeam->slug.current == $teamSlug || awayTeam->slug.current == $teamSlug)\n  && ($homeTeam == null || homeTeam._ref == $homeTeam)\n  && ($homeTeamSlug == null || homeTeam->slug.current == $homeTeamSlug)\n  && ($awayTeam == null || awayTeam._ref == $awayTeam)\n  && ($awayTeamSlug == null || awayTeam->slug.current == $awayTeamSlug)\n  && ($date == null || date == $date)\n  && ($matchDay == null || matchDay == $matchDay)\n] | order(matchNumber asc) [$offset...$limit] {\n  _id,\n  matchDay,\n  matchNumber,\n  date,\n  time,\n  location,\n  homeScore,\n  awayScore,\n  status,\n  \"homeTeam\": homeTeam-> {\n    _id,\n    name,\n    \"logo\": logo.asset->url,\n  },\n  \"awayTeam\": awayTeam-> {\n    _id,\n    name,\n    \"logo\": logo.asset->url,\n  },\n  competition,\n}": MATCHES_QUERYResult;
    "count(*[_type == \"match\"\n  && ($status == null || status == $status)\n  && ($competitionId == null || competition._ref == $competitionId)\n  && ($competitionSlug == null || competition->slug.current == $competitionSlug)\n  && ($team == null || homeTeam._ref == $team || awayTeam._ref == $team)\n  && ($teamSlug == null || homeTeam->slug.current == $teamSlug || awayTeam->slug.current == $teamSlug)\n  && ($homeTeam == null || homeTeam._ref == $homeTeam)\n  && ($homeTeamSlug == null || homeTeam->slug.current == $homeTeamSlug)\n  && ($awayTeam == null || awayTeam._ref == $awayTeam)\n  && ($awayTeamSlug == null || awayTeam->slug.current == $awayTeamSlug)\n  && ($date == null || date == $date)\n  && ($matchDay == null || matchDay == $matchDay)\n])": MATCHES_COUNT_QUERYResult;
    "*[_type == \"match\" && id == $id][0] {\n  _id,\n  name,\n  slug,\n  abbreviation,\n  yearFounded,\n  foundedYear,\n  primaryColor,\n  secondaryColor,\n  country,\n  state,\n  headCoach,\n  asstHeadCoach,\n  email,\n  phone,\n  url,\n  isActive,\n  \"logo\": logo.asset->url,\n  \"bannerImage\": bannerImage.asset->url,\n  players[] {\n    name,\n    number,\n    positions,\n    isCaptain,\n    \"photo\": photo.asset->url,\n  },\n  socialLinks {\n    instagram,\n    youtube,\n    tiktok,\n    twitter,\n  },\n}": MATCH_QUERYResult;
    "*[_type == \"team\" && isActive == true && slug.current == $slug][0] {\n  _id,\n  name,\n  slug,\n  abbreviation,\n  yearFounded,\n  foundedYear,\n  primaryColor,\n  secondaryColor,\n  country,\n  state,\n  headCoach,\n  asstHeadCoach,\n  email,\n  phone,\n  url,\n  isActive,\n  \"logo\": logo.asset->url,\n  \"bannerImage\": bannerImage.asset->url,\n  players[] {\n    name,\n    number,\n    positions,\n    isCaptain,\n    \"photo\": photo.asset->url,\n  },\n  socialLinks {\n    instagram,\n    youtube,\n    tiktok,\n    twitter,\n  },\n}": TEAM_QUERYResult;
    "*[_type == \"team\" && isActive == true] | order(name asc) {\n  _id,\n  name,\n  slug,\n  abbreviation,\n  primaryColor,\n  secondaryColor,\n  country,\n  \"logo\": logo.asset->url,\n}": TEAMS_QUERYResult;
  }
}
